before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./
    binary: yatas
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^style'
      - '^refactor'
      - '^build'
      - '^ci'
      - '^chore'

brews:
- name: yatas
  homepage: https://github.com/stangirard/yatas
  tap:
    owner: stangirard
    name: homebrew-tap
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"  
nfpms:
  - maintainer: stan@primates.dev <stan@primates.dev>
    description: Aws Cost Report
    homepage: https://github.com/stangirard/yatas
    license: Apache 2.0
    file_name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    formats:
      - deb